name: .NET Windows Forms CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_NAME: fuj.sln
  PROJECT_DIR: fuj
  RUNTIME_ID: win-x64
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    # 步骤 1：检出代码
    - uses: actions/checkout@v4

    # 步骤 2：安装 .NET 8 SDK（包含 Windows 桌面组件）
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 步骤 3：验证工作负载
    - name: Verify SDK workloads
      run: dotnet workload list

    # 步骤 4：恢复依赖
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}

    # 步骤 5：构建项目
    - name: Build solution
      run: |
        dotnet build ${{ env.SOLUTION_NAME }} `
          -c ${{ env.BUILD_CONFIGURATION }} `
          -p:Platform=${{ env.RUNTIME_ID }} `
          --no-restore

    # 步骤 6：发布应用
    - name: Publish application
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        dotnet publish ${{ env.SOLUTION_NAME }} `
          -c ${{ env.BUILD_CONFIGURATION }} `
          -r ${{ env.RUNTIME_ID }} `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -p:DebugType=None `
          -o ../publish

    # 步骤 7：上传产物
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: |
          publish/*.exe
          publish/*.dll
        retention-days: 7
