name: Windows Forms CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_PATH: "fuj/fuj.csproj"  # 指向具体的项目文件
  BUILD_CONFIGURATION: "Release"
  RUNTIME_ID: "win-x64"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # 确保与项目目标框架一致

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build project
      run: |
        dotnet build ${{ env.PROJECT_PATH }} \
          -c ${{ env.BUILD_CONFIGURATION }} \
          --no-restore

    - name: Publish application
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} \
          -c ${{ env.BUILD_CONFIGURATION }} \
          -r ${{ env.RUNTIME_ID }} \
          --self-contained true \
          -p:PublishSingleFile=true \
          -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: ./publish
