name: Windows Forms CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_PATH: "fuj/fuj.csproj"
  BUILD_CONFIGURATION: "Release"
  RUNTIME_ID: "win-x64"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 修复点：使用 PowerShell 正确的多行语法
    - name: Build project
      shell: pwsh
      run: |
        dotnet build ${{ env.PROJECT_PATH }} `
          -c ${{ env.BUILD_CONFIGURATION }} `
          --no-restore

    - name: Publish application
      shell: pwsh
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} `
          -c ${{ env.BUILD_CONFIGURATION }} `
          -r ${{ env.RUNTIME_ID }} `
          --self-contained true `
          -p:PublishSingleFile=true `
          -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: ./publish
