name: Windows Forms CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_PATH: "fuj/fuj.sln"
  PROJECT_DIR: "fuj"
  BUILD_CONFIGURATION: "Release"
  RUNTIME_ID: "win-x64"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ${{ env.PROJECT_DIR }}
      run: dotnet restore

    # 关键修改：使用 Any CPU 平台配合运行时标识符
    - name: Build solution
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        dotnet build `
          -c ${{ env.BUILD_CONFIGURATION }} `
          -p:Platform="Any CPU" `
          -p:RuntimeIdentifier=${{ env.RUNTIME_ID }} `
          --no-restore

    - name: Publish application
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        dotnet publish `
          -c ${{ env.BUILD_CONFIGURATION }} `
          -p:Platform="Any CPU" `
          -p:RuntimeIdentifier=${{ env.RUNTIME_ID }} `
          --self-contained true `
          -p:PublishSingleFile=true `
          -o ../publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: publish
