name: Windows Forms CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_NAME: fuj.sln
  PROJECT_NAME: fuj.csproj
  RUNTIME_ID: win-x64
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    # 步骤 1：检出代码
    - uses: actions/checkout@v4

    # 步骤 2：安装 .NET 和 Windows 桌面工作负载
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
        include-prerelease: false

    - name: Install Windows Desktop SDK
      run: dotnet workload install windowsdesktop

    # 步骤 3：解决方案级恢复
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}

    # 步骤 4：构建解决方案
    - name: Build Solution
      run: |
        dotnet build ${{ env.SOLUTION_NAME }} `
          -c ${{ env.BUILD_CONFIGURATION }} `
          -p:Platform=x64 `
          --no-restore

    # 步骤 5：发布应用程序
    - name: Publish Application
      working-directory: fuj
      run: |
        dotnet publish ${{ env.PROJECT_NAME }} `
          -c ${{ env.BUILD_CONFIGURATION }} `
          -r ${{ env.RUNTIME_ID }} `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -p:DebugType=None `
          -o ../publish

    # 步骤 6：上传构建产物
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: |
          publish/*.exe
          publish/*.dll
        retention-days: 7
